// src/app/layout.js

import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={"font-customfont"}>
        <NavbarWrapper>
          {children}
        </NavbarWrapper>
      </body>
    </html>
  );
}
